# config.yaml

constants:
  output_directory: /home/hlavsja3/scent/vscht_scripts
  output_file_name: out
  t1_shift: -500
  system_number: 2
  box_t1: 2
  box_t2: 20
  dot_product_threshold: 0.8
  m_z_index: -1
  area_box_t1: 4
  area_box_t2: 100
  area_threshold: 0.95
  visualize_area: False

calibration_compounds:
  - Heptacosane
  - Tetradecane, 1-chloro-
  - 2,5-pyrrolidinedione, 3-decyl-
  - 2,5-pyrrolidinedione, 3-dodecyl-
  - 2,5-pyrrolidinedione, 3-tetradecyl-
  - Squalene
  - Cholesterol
  - Hexadecanoic acid, dodecyl ester
  - 9-Hexadecenoic acid, tetradecyl ester
  - Hexadecanoic acid, tetradecyl ester
  - 9-Hexadecenoic acid, hexadecyl ester
  - Hexadecanoic acid, hexadecyl ester
  - 9-Hexadecenoic acid, octadecyl ester
  - Nonacosane
  - 1-Dodecanol
  - Dodecane, 1-chloro-
  - Dodecanamide, N-allyl-
  - 2,5-pyrrolidinedione, 3-hexadecyl-
  - Fumaric acid, 2-dimethylaminoethyl heptyl ester
  - Cholesta-3,5-diene (izomer 2)
  - Cholesta-3,5-dien-7-one
  - Cholesta-4,6-dien-3-one
  - Cholest-4-en-3-one
  - Hexadecanoic acid, octadecyl ester

triangles:
  - 3 37 38
  - 37 38 69
  - 10 37 69
  - 10 11 37
  - 11 37 41
  - 11 13 41
  - 12 13 41
  - 12 41 48
  - 31 41 48
  - 31 34 41
  - 10 67 69
  - 10 11 67
  - 11 13 67
  - 12 13 67
  - 12 48 67
  - 21 48 67
  - 21 31 48
  - 21 31 34

